from sentence_transformers import SentenceTransformer
from sbert import load_sbert 
from sentence_transformers import util

import requests
import json
from scipy.spatial.distance import cdist
from openai import AzureOpenAI
import numpy as np
import time 

import tkinter as tk
from tkinter import scrolledtext

model_path1 = "C:/Users/Siemens/Documents/TFE_Nick_Kuijpers/LoRa_GPL/GPL_LoRA/output/QKV/LoRa_r16_a64/Siemens/distilbert-base-uncased/checkpoints/100"
model_path2 = "C:/Users/Siemens/Documents/TFE_Nick_Kuijpers/LoRa_GPL/GPL_LoRA/output/QKV/LoRa_r16_a64/Siemens/distilbert-base-uncased/checkpoints/3500"

pooling = None
max_seq_length = 350
#         "SITRANS LR120 is a W band FMCW radar level transmitter, packaged\nin a hermetically sealed PVDF enclosure for years of trouble-free reli\u0002able measurement service.\n4 to 20 mA loop powered with HART [optional 4-wire Modbus RTU],\nproviding accurate level measurement to ranges of 30 m (98.4 ft).\nIts long range, narrow beam make LR120 suitable for wet wells with\nobstructions or solids level measurement, for example aggregates or\nplastic pellets. Programming is convenient using the Bluetooth con\u0002nection and SITRANS mobile IQ application on your smart device",
# What outdoor radar transmitter can I use
# I need an outdoor conductor which can accurately reach 30m of flow measurements
model1: SentenceTransformer = load_sbert(model_path1, pooling, max_seq_length)
model2: SentenceTransformer = load_sbert(model_path2, pooling, max_seq_length)
test = {
    "I need an outdoor conductor which can accurately reach 30m of flow measurements": 
        [
        "A Design Specification (DS) is produced to analyze the technical development which will be implemented to meet the User Requirements Specification (URS). It mainly focuses on the technical implementation of all the different system related functions, and how these listed functions will project themselves within the deployed architecture. The Design Specification is produced by the system supplier and approved by the client. It thus serves as an agreement on how the user requirements will be implemented in a technical manner.",
        "Opcenter EX PH has out-of-the-box configurable OPC functionality, the EPE and Equipment Module will be used in the PI to interact with the process via OPC UA. The Equipment Model will synchronize with the OPC server in an automated way via the synchronization tags, or in a manual way via an EPE tag (read or write action) in the PI. Equipment properties and states can then be read out as usual via Equipment tags in the PI.",
        "The WSM5 is a measuring instrument used for the physically correct acquisition of energy consumption. The device consists of a flow measuring section made of high-tech plastic, 2 ready connected temperature sensors, and an electronic unit which calculates the energy consumption from the flow and the temperature differential. The WSM5.. is of compact design and therefore ideally suited for use in apartments.",
        "The control system typically stores and archives alarm data in different servers, depending on the WinCC architecture. The WinCC Connectivity Pack creates an abstraction layer on top of the WinCC Database that allows both the runtime and archived WinCC data to be accessed using a single entity endpoint. This interface is enabled by an OLE DB provider integrated into the WinCC Connectivity Pack. That way, alarm data (both archived and runtime) can be efficiently centralized and extracted using simple SQL queries.",
        "SITRANS LR120 is a W band FMCW radar level transmitter, packaged\nin a hermetically sealed PVDF enclosure for years of trouble-free reli\u0002able measurement service.\n4 to 20 mA loop powered with HART [optional 4-wire Modbus RTU],\nproviding accurate level measurement to ranges of 30 m (98.4 ft).\nIts long range, narrow beam make LR120 suitable for wet wells with\nobstructions or solids level measurement, for example aggregates or\nplastic pellets. Programming is convenient using the Bluetooth con\u0002nection and SITRANS mobile IQ application on your smart device",
        "RUGGEDCOM CROSSBOW is a proven enterprise-class solution for secure remote and \nlocal user access and management of intelligent electronic devices according to \nrecognized cybersecurity standards, e.g., NERC CIP and IEC 62443. It allows for the \nautomation of passwords, firmware, configuration, and data management of field \nassets and provides a comprehensive reporting mechanism for regulatory compliance. \nOperators of industrial control systems in critical infrastructure, such as electric power \nutilities, renewables, rail, oil and gas, etc., can benefit from the flexibility, scale, and \nmost importantly the security offered by RUGGEDCOM CROSSBOW.",
        "The software option SINAMICS Motor Control Extended for \nSINAMICS G220 enables high-performance encoderless \nclosed-loop control of synchronous reluctance motors from \nstandstill, by enabling pulse technique at very low speeds.",
        "The SINAMICS drive system allows input and output signals of \ndifferent SINAMICS Drive Software functions to be intercon\u0002nected with one another. In addition to setting parameters, the \nability to interconnect signals is an additional option of adapting \nSINAMICS Drive Software functions to address the particular ap\u0002plication. Signal connection enables flexible adaptation of \nSINAMICS to a wide range of the customer requirements.",
        "With Innomotics motor, Siemens has the most comprehensive portfolio \nof electric motors worldwide. From energy-efficient, low-voltage \nmotors through servomotors with high dynamic performance up \nto well-proven DC motors and powerful high-voltage motors. \nInnovative drive technology for all industries, applications and \npower classes",
        "Innomotics Low-Voltage Motors are the right choice for solving \ndrive tasks efficiently and reliably. In contrast to Motion Control \nmotors, which are additionally characterized by very high dy\u0002namic response and precision, the more favorably priced low\u0002voltage motors are predestined for continuous or periodic, as \nwell as powerful motions with fixed or variable speed, such as in \npumps, fans, compressors, conveyor belts, lifts, hoisting and \ntraversing gear, winders, mixers, kneaders and centrifuges.\nInnomotics Low-Voltage Motors are characterized by very high \nreliability, ruggedness, and efficiency in operation.",
        "The RD300 is a remote display for level, flow, pressure, weighing,\nand other process instruments. This display also acts as a multi-pur\u0002pose, easy to use rate/totalizer ideal for flow rate, total, and control\napplications.\nData can be remotely collected, logged and presented on your local\ncomputer using the free RD software available via USB drive.\nThe display accepts a single or dual input of current and voltage.\nThis makes the RD300 an ideal fit for use with most field instru\u0002ments.\nThe RD300 can be set up as a standard panel mount, or combined\nwith optional enclosures to allow it to house up to 6 displays",
        "The RD100 is very versatile. It can be installed indoors or outdoors,\nin hot or cold environments, and in safe or hazardous areas.\nIt has been approved by FM and CSA as Intrinsically Safe and non\u0002incendive, and operates from -40 to +85 ºC\n(-40 to +185 ºF), adding only 1 V to the loop.\nCalibration consists of a quick two-step process involving the adjust\u0002ment of only two non-interacting potentiometers",
        "SITRANS LR500 series are 80 GHz radar level transmitters for continuous monitoring of liquids, slurries, and solids in storage and process vessels including high temperature and pressure, to a range of 120 m (393 ft)",
        "EchoMax XRS-5 ultrasonic transducer provides reliable, continuous level monitoring of liquids and slurries in narrow lift stations/wet wells, flumes, weirs and filter beds using a beam angle of just 10° and a CSM rubber face.",
        "The XRS-5 is a non-contacting sensor with a measuring range from 0.3 to 8 m (1 to 26 ft). Advanced echo processing ensures reliable data even in conditions with obstructions, turbulence, and foam.\nThe hermetically sealed CSM rubber face and the PVDF copolymer enclosure are designed for maximum resistance to methane, salt water, caustics, and harsh chemicals common to wastewater install\u0002ations. With an IP68 degree of protection, this rugged sensor is fully submersible in the event of flood conditions. Use a submergence shield if full submergence is possible in the application. A submer\u0002gence shield will maintain a high level reading output during sub\u0002merged conditions.",
        "Distribution-system automation from Siemens considerably optimizes the reliability and availability of your energy distribution\nsystems. Here, the functionality extends from the acquisition of network data, telemonitoring and remote control up to fully\nautomated applications such as high-speed FISR (Fault Isolation and Service Restoration), Volt-Var Control and similar.",
        "SITRANS LR510 threaded lens antenna provides continuous monitoring of liquids, including corrosive liquids, and slurries to a range of\n30 m (98 ft).The small process connection makes it ideal for applica\u0002tions with challenging mounting conditions",
        "SITRANS LR530 flange encapsulated antenna provides continuous\nmonitoring of liquids and slurries to a range of 120 m (394 ft).The\nPTFE lens and integrated gasket is easy to clean and ideal for highly\ncorrosive media.",
        "SITRANS LR580 lens antenna provides continuous monitoring of\nsolids or liquids to a range of 120 m (394 ft). The design includes an\naimer feature as well as integrated air purge connection for invent\u0002ory measurement applications in silos. It is also well suited to high\ntemperature applications in the cement and power industries.",
        "SITRANS LT500 is a versatile, single and multi-vessel level monit\u0002or/controller for virtually any application in a wide range of indus\u0002tries. SITRANS LT500 will monitor open channel flow and features advanced relay alarming and pump control functions as well as volume conversion. Key Applications: wet wells, flumes/weirs, bar screen control, hop\u0002pers, chemical storage, liquid storage, crusher bins, dry solids stor\u0002age",
        "Process protection devices act as early warning systems to avoid costly process interruptions and breakdowns of equipment. Non\u0002contacting motion sensors detect changes in motion and speed of conveying, reciprocating and rotating machinery. Non-invasive acoustic sensors detect inaudible, high frequency acoustic emissions generated by friction and impact, caused by\nmaterials in motion. They can detect conditions of flow/no flow or high/low flow, to warn of blockages, product absence or equipment failure. They are located outside of the process, accurately detecting conditions without wear on the sensor. Motion sensors can warn in case of equipment malfunction and shut\ndown machinery in case of a slowdown or failure. They are rugged and perform even in harsh industrial conditions. Most of the MFA 4p motion sensing probes, as well as the SITRANS WM100, can be mounted up to 100 mm (4 inch) from the ferrous target, reducing the chance of damage to the probe and the equipment. The probes are not affected by moisture or dust build-up.",
        "EchoMax XPS transducers use ultrasonic technology to measure\nlevel in a wide range of liquids and solids.\nBenefits\n• Integral temperature compensation\n• Low ringing effect reduces blanking distance\n• Optional foam facing for dusty applications\n• Self-cleaning and low-maintenance\n• Chemically resistant\n• Hermetically sealed\nApplication\nXPS transducers can be fully immersed, are resistant to steam and\ncorrosive chemicals, and can be installed without flanges.\nThe XPS series offers versions for various measuring ranges up to 30\nm (100 ft) and up to a max. temperature of 95 °C (203 °F).\nDuring operation, the EchoMax transducers emit acoustic pulses in a\nnarrow beam. The level monitor measures the propagation time\nbetween pulse emission and its reflection (echo) to calculate the dis\u0002tance.",
        "SITRANS WF300 series are low to medium capacity flowmeters for\nvarious product sizes, densities, and fluidities.\nBenefits\n• For specialized pre-feed applications\n• Sensing element mounted outside process\n• Flowrates from 0.2 to 300 t/h (0.2 to 330 STPH)\n• Continuously monitoring of the material flow without interrupting\nthe process\n• Dust-tight construction: suitable for use in hazardous areas and in\nwashdown applications that require frequent cleaning\n• Minimal maintenance or recalibration after the initial installation\nand material tests\nApplication\nWith weighing mechanics located externally, the WF300 series solids\nflowmeters are unaffected by corrosive, abrasive, or hot materials.\nHandling a wide range of product sizes, densities, and fluidities\nincluding fine powders such as cement, they operate at process tem\u0002peratures to 230 °C (450 °F). The flowmeters help to improve final\nproduct, increase operating efficiency, and realize significant cost\nsavings.\nOperating with the appropriate SITRANS WFS sensing head and a\nmicro-processor-based integrator package, the WF300 series flow\u0002meters provide a display of the flow rate, totalized flow, and alarms.\nOutputs are 0/4 to 20 mA proportional to rate, and open collector\noutput for remote totalization.",
        "Milltronics WD600 is a light- to medium-duty slider bed belt scale\nused for process and load-out control in manufacturing, including\nthe food, pharmaceutical and tobacco industries.\nBenefits\n• Simple installation\n• Long weigh span for more retention time on load cells\nApplication\nWD600 works with an existing flat belt conveyor and the selected\nSiemens integrator. As material is moving along the conveyor belt\nand travels over the belt scale, it exerts a force proportional to the\nmaterial load through the suspended weighbridge to the load cells.\nWD600 reacts only to the vertical component of the applied force.\nThe resulting movement in each load cell is sensed by its strain\ngauges. When the strain gauges are excited by voltage from the\nelectronic integrator, they produce an electrical signal proportional\nto weight, which is then applied to the integrator.\nThe vertical movement of the load cells is limited by the positive\noverload stop incorporated into the design of the load cell mount.",
        "3WA air circuit breakers provide enhanced protective functions and increased selectivity to ensure maximum system availability. Their \nrobust mechanisms and outstanding product quality are highly effective in demanding heavy-duty applications. With a 3WA air circuit \nbreaker in your switchgear, you can efficiently retrofit a 3WL air circuit breaker, saving time and money",
        "The SITRANS LR250 Hygienic Encapsulated Antenna is a 2-wire\n25 GHz pulse radar level transmitter with sanitary and hygienic\napprovals for continuous monitoring of liquids, slurries, and pastes\nwithin the food, beverage, chemical, and pharmaceutical industries\nto a range of 20 m (66 ft) (antenna dependent).",
        "SITRANS LR250 includes a graphical local user interface (LUI) that\nimproves set-up and operation by including an intuitive Quick Start\nWizard, and echo profile displays for diagnostic support. Startup is\neasy using the Quick Start wizard with few parameters required for\nbasic operation.\nThe 25 GHz frequency creates a narrow, focused beam allowing for\nsmaller antenna options and decreasing sensitivity to obstructions.\nSITRANS LR250’s unique design allows safe and simple programming using the Intrinsically Safe handheld programmer without\nhaving to open the instrument’s lid.\nSITRANS LR250 measures superbly in small vessels and in tanks/vessels up to 20 m (66 ft) on materials with dk > 1.6.",
        "SITRANS FM TRANSMAG 2 with the SITRANS FM MAG 911/E sensor is\na flowmeter using alternating (AC) field technology where the mag\u0002netic field strength is much higher than conventional magnetic flow\u0002meters with pulsed DC field technology.\nThe TRANSMAG 2 is a microprocessor-based transmitter with a built\u0002in alphanumeric display in several languages. The transmitters eval\u0002uate the signals from the associated electromagnetic sensors and also fulfill the task of a power supply unit which provides the mag\u0002net coils with a constant current.\nThe magnetic flux density in the sensor is additionally monitored by reference coils. Further information on connection, mode of operation and installa\u0002tion can be found in the data sheets for the sensors.",
        "The electromagnetic sensor SITRANS FM MAG 1100 F is designed to\nmeet applications in the food and beverage industry.\nBenefits\n• Sensor sizes: DN 10 to DN 100 (3/8\" to 4\")\n• AISI 316 stainless steel enclosure\n• Sensor: Hygienic connection, 3A approval\n• Sanitary design for CIP/SIP cleaning\n• Easy commissioning, the SENSORPROM unit automatically updates\nsettings\n• Hose proof IP67/NEMA 6 enclosure rating\n• Designed that patented in-situ verification can be conducted.\nUsing SENSORPROM fingerprints.\nApplication\nThe main applications of the SITRANS FM electromagnetic sensors\ncan be found in the following fields:\n• Food industry\n• Beverage industry\n• Pharmaceutical industry",
        "MAG 8000 is a comprehensive meter which intelligent information\nand high performance measurement as well as the easy to install\nconcept take cost of ownership and customer service to a new level\nfor water meter.",
        "The SITRANS FM100 is an electromagnetic flow sensor in a compact\ndesign for basic applications in the process and OEM industry.",
        "The SITRANS FST020 is the basic device for simple and cost-effective\nsolution for FSS100 inline and FSS200 clamp on sensors. With the SITRANS FST020 only a single-path measuring is possible.\nAs a single-path device, it is suitable for flow measurement on\nliquids that do not require temperature or viscosity consideration\nand where highest accuracies are not required.\nThe SITRANS FST020 is part of a digital platform based on the latest\ndevelopments within Digital Signal Processing (DSP) technology – engineered for high measuring performance, fast response to\nstep changes in flow, high immunity against process noise and simplicity in installation, commissioning and maintenance.\nThe FST020 transmitter delivers standard parameter measurements\ni.e. volume flow, flow speed or sound velocity by analog outputs\nand Modbus communication.",
        "SITRANS FST030 can be used together with FSS200 clamp-on\nsensors and with the FSS100 inline sensors. \nThe SITRANS FST030 transmitter delivers true multi-parameter\nmeasurements i.e. volume flow, standard volume flow, density,\nmass flow, fluid sound velocity and temperature. The multiple outputs and bus communication mean that all primary process information can be read either instantaneously (10 ms update) or periodically as required by plant operations.\nThe SITRANS FST030 can be used with the FSS100 sensors\n(SONOKIT).To get a SITRANS FS130 system, the SITRANS FST030\ntransmitter and FSS100 sensors must be ordered separately. The\nFSS100 sensors are tested and quality controlled individually and do\nnot require to be paired or calibrated with an FST030 transmitter.\nThe transmitter related to this system is the SITRANS FST030.",
        "The 7PG111 and 7PG112 AR (auxiliary relay) range of electro\u0002mechanical relays are available with up to eight self, hand or\nelectrically reset contacts. They can be supplied with various\ncombinations of contact, flag and reset arrangements.\nAR relays are voltage operated from either AC or DC supplies.\nRelays may be built with or without a flag indicator.\nFeatures:\nType AR relays are a range of electro-mechanical relays with up\nto 8 contacts and complying to BS142. They can be supplied\nin most combinations of contact, flag and reset arrangements.\nThey are used wherever there is a need for additional contacts.\nThe relays are identified by a series of numbers and letters\nwhich define important relay features",
        "Type XR relays are developments for specific applications from\nthe AR relay range. They are electro-mechanical relays with a\nconsistent positive action, a long service life, and comply with\nBS142 and IEC 255 standards. The XR range is used as Inter\u0002posing, Supervision, or Special Purpose Relays.\nInterposing Relays: XR105, XR106, XR107, XR205, XR206\n• The interposing relays are intended for the remote control\noperation of switchgear over pilot wires with a maximum\nresistance of 200 Ω. The relays are designed so that they are\nnot susceptible to certain AC voltage levels which may be\ninduced onto the pilot wires.\nSupply Supervision Relays: XR152, XR153\n• The supervision relays are designed to monitor DC voltages.\nThey have a low operating current, specific settings, time\ndelayed drop-off, a mechanical flag indicator which shows on\nde-energization and contacts for the ability to initiate remote\nalarms.\nTrip Circuit Supervision Relays: XR151, XR250, XR251, XR350,\nXR351\n• These relays are for the monitoring of the circuit breakers trip\ncircuit to ensure integrity at all times. There are differing preferences for monitoring a trip circuit and our range is designed\nto meet these requirements.",
        "Interposing relays are used for remote control of switchgear\nand associated equipment over pilot wires or cross-site cables.\nType XR205 and XR206 are two element versions of the XR105\nand XR106 respectively with the same performance. Type XR\nrelays are developments for specific applications from the type\nAR (7PG11) relay range. They are electro-mechanical relays with\na consistent positive action, a long service life and complying\nwith BS142",
        "SITRANS FCS500 sensor is the universal Coriolis flow sensor for\nroutine and hygienic applications.\nFeatures:\n• Dual curved AISI 316L stainless steel tubes with polished option\n• Nominal sizes: DN 10 to DN 80 \n• Process connection: flange, thread, or a selection of hygienic fit\u0002tings \n• Hygienic approvals for food, beverage, and pharmaceutical sectors\n• Versatile solution with superior turndown and low pressure loss\n• Combination with compact or remote transmitters",
        "SITRANS FCS700 sensor is the grande Coriolis flow sensor for large\npipes and high flows.\nFeatures:\n• Dual curved AISI 316L stainless steel or alloy 22 tubes with optim\u0002um decoupling from external influences\n• Nominal sizes: DN 100 to DN 200\n• Process connection: flanges \n• Energy efficient low pressure loss design with short tube paths and\nlarge tube diameter\n• High power tube driver for dependable measurements in high\ndamping applications\n• Combination with compact or remote transmitters",
        "The flowmeter systems of the SITRANS FC600 series are the resistant\nCoriolis multi-parameter flowmeter for extreme conditions. \nThe Coriolis flowmeters of this serie are rugged with superior per\u0002formance under very tough operating conditions. \nThey are formed by one FCS600 sensor and one FCT transmitter:\n• SITRANS FC620 is the combination of the FCS600 sensor and the\nFCT020 transmitter\n• SITRANS FC640 is the combination of the FCS600 sensor and the\nFCT040 transmitter",
        "FCT020 is the standard transmitter, suitable for general purpose\napplications. It delivers accurate and precise measurements of mass\nflow rate, density, temperature and volume flow rate.\nThe FCT020 transmitter is available in compact or remote design and\ncan be combined with all SITRANS FC sensors. The selection is made\nwithin the complete SITRANS FC ordering code.\nSpare transmitters are selected using the SITRANS FC ordering code,\nbut with no sensor selected.",
        "Tube health check monitors key diagnostics, including tube stiffness,\ndriver and pickups. Self-verification alerts to potential performance\nissues due to unplanned process events, for example gas or vapor\nbreakout, or solid deposits building up in the tubes. The user defines\nverification frequency and alarm behavior. Verification results indicate whether preventive maintenance action is required.",
        "SITRANS FCS100 sensor is the precision Coriolis flow sensor for low\nflow applications.\nFeatures:\n• Possibly the most compact dual curve Coriolis flow sensor\n• Nominal sizes: DN 1 to DN 8\n• Process connection: flange, thread, or hygienic clamp \n• Install in tight spaces with no inlet and outlet restrictions\n• Sizes to suit pilot plants, R & D labs, and high value fluid additives\n• FCS100 sensors always combine with a remote transmitter via a\nconnecting cable\n• Installation of sensor and transmitter in different locations",
        "SITRANS FC is the range of Siemens Coriolis mass flowmeters that\nprovides high performance process measurements. The extensive\nportfolio provides multi-parameter measurement solutions for all fluid\ntypes, including liquids, gases and multi-phase fluids.\nPrimary measurements of mass flow, density and temperature are\navailable immediately on device start-up.\nSITRANS FC also calculates multiple secondary measurements\nincluding:\n• Fraction (or concentration)\n• Liquid volume flow\n• Normal (standard) volume flow of gases\n• Viscosity (requires external input)\n• Thermal energy",
        "The OXYMAT 64 gas analyzer is used for the trace measurement of\noxygen.\nBenefits\n• High linearity\n• Compact design\n• Open interface architecture (RS 485, RS 232, PROFIBUS)\n• SIPROM GA network for maintenance and service information\n(option)\nApplication\nProduction of technical gases\n• Measurements in N2 and CO2\nWelding\n• Measurements in protective gases during welding of highly alloyed\nsteels, titanium, etc.\nSystems for air separation\n• Measurements in N2 and in inert gases (e.g. Ne, Ar)\nMeasurements in CO2\nFood production\n• Measurement in CO2 (e.g. breweries)\nElectronics industry\n• Low-pressure version with pump\nFlow soldering systems",
        "The new magnetic flow meter transmitter model SITRANS FMT020 is\na high performance, robust and intelligent product, designed to fit\nperfectly for a wide area of process applications that require accurate, and reliable flow measurement of conductive fluids. \nThe SITRANS FMT020 is the next generation successor for the well\u0002proven MAG 5000 and MAG 6000 transmitter series.  The FMT020\nretains all the unique features of this transmitter series such as the\nflexible installation concept with common housing for compact and\nremote mounting.  It also maintains the modular design supporting\neasy exchangeability of the transmitter as well as the add-on com\u0002munication modules, or the Sensorprom memory unit for fast commissioning, instant measurement, and data storage. The transmitter can be configured locally via display and remotely\nover Fieldbus or Webserver. EDDs are available for SIMATIC PDM,\nAMS Device Manager, and AMS Trex Device Communicator, plus\nDTMs for FDTs (Field Device Tools).",
        "Siemens 3MT7 capacitor duty contactors \nare specially designed to meet stringent \nrequirements of capacitor switching as \ndeliberated above. These contactors are \nfitted with front- mounted block of 3 early \nmake auxiliary contact in series with quick \ndischarge damping six-resistors-2 per \nphase to limit peak current to value within \ncontactor making capacity. The damping \nresistors are activated via early make \nauxiliary contacts before the main contacts \nclose. During switching, after attenuation \nof the peak current, they are decoupled \nagain",
        "Pointek CLS300 is an inverse frequency shift\ncapacitance level and material detection switch with optional\nrod/cable choices and configurable output. CLS300 is ideal for\ndetecting liquids, solids, slurries, foam, and interfaces in demanding\nconditions where high pressure and temperatures are present and\nhas the ability to tune out buildup on the probe",
        "Pointek CLS200 is a versatile inverse frequency\nshift capacitance level and material detection switch with optional\nrod/cable choices and configurable output. CLS200 is ideal for\ndetection of liquids, solids, slurries, foam, and interfaces and has\nthe ability to tune out buildup on the probe.",
        "SITRANS LR140 is a 2 wire loop powered radar transmitters for continuous level measurement of liquids and slurries to a range of 8 m\n(26 ft). SITRANS LR140 is a W band FMCW radar level transmitter, packaged\nin a chemically resistant enclosure with PVDF sensor for years of\ntrouble-free reliable measurement service.\n4 to 20 mA loop powered, it provides accurate level measurement\nto ranges of 8 m (26 ft). Measurement is possible, non-intrusively,\nthrough plastic vessel tops for easy installation. Programming is\nconvenient using the Bluetooth connection and SITRANS mobile IQ\napplication on your smart device.",
        "SITRANS LR200 is a 2-wire, 6 GHz pulse radar level transmitter for\ncontinuous monitoring of liquids and slurries in process vessels\nincluding high temperature, pressure, agitation, and turbulence to a\nrange of 20 m (65 ft). ming using the Intrinsically Safe handheld programmer without\nhaving to open the instrument’s lid. It also features a built-in alpha\u0002numeric display in four languages.\nThe SITRANS LR200 has a standard Uni-Construction polypropylene\nrod antenna that offers excellent chemical resistance and is hermet\u0002ically sealed. The Uni-Construction antenna features an internal,\nintegrated shield that eliminates vessel nozzle interference.\nStartup is easy with as few as two parameters for basic operation.\nInstallation is simplified as the electronics are mounted on a rotat\u0002ing head that swivels, allowing the instrument to line up with con\u0002duit or wiring connections or simply to adjust the position for easy viewing. SITRANS LR200 features Process Intelligence signal-pro\u0002cessing technology for superior reliability.",
        "SITRANS WW200 is a low- to medium-capacity weighfeeder used for minor ingredient additives. SITRANS WW200 has been field tested and proven in hundreds of\napplications. The unit can be customized to meet exact application needs. Stain\u0002less or mild steel units are available in open or enclosed styles. Cus\u0002tom lengths, belt types, inlet configurations, drives, and other options are available to meet your requirements. Its cantilevered mechanical design provides for quick belt removal and easy maintenance. It is designed to eliminate material build-up, ensuring high accuracy and reliability. The unique weigh system reduces dead load and applies live load directly to two platform load\ncells. Load cells are externally mounted for easy access and main\u0002tenance. Standard components include an anti-static food grade belt option, horizontal slider bars for self-cleaning and minimal product build up, belt tracking rollers, belt scraper, and plow for self-cleaning.",
        "SITRANS WS300 is a low- to high-resolution shaft-driven speed sensor. SITRANS WS300 speed sensor operates in conjunction with a con\u0002veyor belt scale, providing a signal to an integrator which computes the rate of material being conveyed. At only 1.22 kg (2.68 lb), it is\none of the lightest and most durable units ever developed for mon\u0002itoring conveyor belt speed. With its rugged cast aluminum hous\u0002ing, it is suitable for outdoor installation, and its low weight pro\u0002longs bearing life. It is directly coupled to a rotating tail or bend pulley shaft to ensure\naccurate belt-travel readout, eliminating problems caused by belt slippage or material build-up. The WS300 converts shaft rotation\ninto a pulse train of 32, 256 pulses per revolution using a high pre\u0002cision rotary optical encoder. The digital signal is transmitted as\nspeed input to any Siemens integrator for calculation of belt speed, flow rate and totalized weight.\nThis low- to high-resolution speed sensor provides a frequency sig\u0002nal proportional to the shaft speed, enabling a range of speeds to\nbe read accurately. The quadrature type shaft encoder prevents erroneous speed signals due to vibration or shaft oscillation. The\nWS300 is easily mounted and is bi-directional for either clockwise or counter-clockwise belt travel.",
        "The ULTRAMAT 6 single-channel or dual-channel gas analyzers operate according to the NDIR two-beam alternating light principle and\nmeasure gases highly selectively whose absorption bands lie in the\ninfrared wavelength range from 2 to 9 μm, such as CO, CO2, NO,\nSO2, NH3, H2O as well as CH4 and other hydrocarbons.\nSingle-channel analyzers can simultaneously measure up to 2 gas\ncomponents, while dual-channel analyzers can simultaneously\nmeasure 3 (or 4 on request) gas components.",
        "Reyrolle has been synonymous with electrical protection devices\nin the sectors of transmission, distribution, and industrial applications for decades. Historically, Reyrolle relays were sold mainly\nin traditional markets but are now sold worldwide as part of the Siemens network",
        "The comprehensive range of Reyrolle products provides the total\nprotection requirements of distribution markets – ranging from\novercurrent protection via transformer protection and voltage\ncontrol to a full spectrum of auxiliary and trip relays. The portfolio includes many famous products such as Argus, Duobias,\nSolkor, Rho.",
        "The Reyrolle 7SR105 relay is a numerical protection relay\nintended for use in motor protection applications. It provides\nextensive functions for a range of applications and is particularly\ncharacterized by a simple and intuitive operation, which signifi\u0002cantly reduces the time required for installation, engineering,\nparameterization, wiring, and commissioning.",
        "The ULTRAMAT/OXYMAT 6 gas analyzer is a practical combination of\ntwo analyzers, ULTRAMAT 6 and OXYMAT 6, in a single enclosure.",
        "The ULTRAMAT 6 measurement channel functions according to the\nNDIR dual-beam differential mode process and highly selectively\nmeasures gases whose absorption bands are in the infrared\nwavelength range between 2 and 9 µm, for example CO, CO2, NO,\nSO2, NH3, H2O as well as CH4 and other hydrocarbons.",
        "The OXYMAT 6 measurement channel is based on the paramagnetic\nalternating pressure method and is used to measure oxygen in\ngases.",
        "SINAMICS is an integral component of the Siemens \"Totally \nIntegrated Automation\" concept. Integrated SINAMICS systems \ncovering configuration, data storage, and communication at \nautomation level ensure low-maintenance solutions with the \nSIMATIC, SIMOTION and SINUMERIK control systems",
        "The SITRANS FMS500 is a magnetic flow meter sensor suitable for\nvolume flow measurement of liquids (conductive) and is the ideal\nproduct for applications in water abstraction, wastewater treatment,\nwater distribution networks, and irrigation.\nThe rugged, fully welded design supports direct burial, constant\nflooding and to stand up a wide range of harsh chemicals found in\nwater-based applications in many different industries.\nDesigned for highly accurate measurement in low-flow conditions,\nthese meters can measure from very low velocities up to 10 m/s, giv\u0002ing it a very wide measurement range.",
        "The new magnetic flow meter transmitter model SITRANS FMT020 is\na high performance, robust and intelligent product, designed to fit\nperfectly for a wide area of process applications that require accur\u0002ate, and reliable flow measurement of conductive fluids. \nThe SITRANS FMT020 is the next generation successor for the well\u0002proven MAG 5000 and MAG 6000 transmitter series.  The FMT020\nretains all the unique features of this transmitter series such as the\nflexible installation concept with common housing for compact and\nremote mounting.  It also maintains the modular design supporting\neasy exchangeability of the transmitter as well as the add-on com\u0002munication modules, or the Sensorprom memory unit for fast com\u0002missioning, instant measurement, and data storage.",
        "SITRANS LCS100 is a point level switch that detects point level in\nliquids, solids, slurries, foam, and interface detection. Its compact\ndesign is ideal for confined spaces with plastic or stainless steel pro\u0002cess connections and flexible rod and cable probe extensions.\nSITRANS LCS100 is used for overflow, high, low, and demand\napplications as well as pump protection. It works in all types of ves\u0002sels, pipes, and silos in a broad range of industries including food,\npharmaceuticals, chemical, petrochemical, water, and machine\nbuilding.",
        "Pointek CLS300 is an inverse frequency shift\ncapacitance level and material detection switch with optional\nrod/cable choices and configurable output. CLS300 is ideal for\ndetecting liquids, solids, slurries, foam, and interfaces in demanding\nconditions where high pressure and temperatures are present and\nhas the ability to tune out buildup on the probe.",
        "Pointek CLS200 is a versatile inverse frequency\nshift capacitance level and material detection switch with optional\nrod/cable choices and configurable output. CLS200 is ideal for\ndetection of liquids, solids, slurries, foam, and interfaces and has\nthe ability to tune out buildup on the probe.",
        "SITRANS LR140 is a 2 wire loop powered radar transmitter for continuous level measurement of liquids and slurries to a range of 8 m\n(26 ft).",
        "SITRANS LR100 is a W band FMCW radar level transmitter, packaged\nin a hermetically sealed PVDF enclosure for years of trouble-free\nreliable measurement service.",
        "Application : Milltronics bend pulleys provide constant belt contact for use with\nSiemens speed sensors. Designed for use in rugged operating envir\u0002onments common to mining, aggregates, cement, minerals, and\nother process industries. They ensure concentric speed sensor rota\u0002tion to reduce pre-mature bearing failure. The use of a bend pulley\ndriven speed sensor ensures no modification is required on any\nexisting conveyor shaft. Options include stainless steel construc\u0002tion, epoxy painting, polymer bearings, self-cleaning style, and\nlagged style.",
        "FCT020 is the standard transmitter, suitable for general purpose\napplications. It delivers accurate and precise measurements of\nmass flow rate, density, temperature and volume flow rate.",
        "The Net Oil Computing (NOC) function provides real-time measurements of water cut and includes American Petroleum Institute\n(API) correction according to API MPMS Chapter 11.1.",
        "Viscosity is sometimes used as reference value to activate other\nprocesses like fluid heating systems.\nThe viscosity estimation is calculated based on a comparison\nbetween measured pressure loss and a calculated value between\ntwo points of the pipe. A differential pressure transmitter is\nrequired to use this function. Its output is connected to the analog\ninput of the FCT040. Based on an iteration process, a viscosity\nvalue is determined.",
        "SITRANS LUT400 are compact, single \npoint, long range ultrasonic controllers \nfor continuous level or volume measurement of liquids, slurries, and solids, \nand high accuracy monitoring of open channel flow",
        "MultiRanger/HydroRanger are versatile \nshort-to medium-range ultrasonic \nsingle and multi-vessel level monitor/\ncontrollers for virtually any application \nin a wide range of industries",
        "SITRANS LT500 is a controller for level, \nvolume, volume flow, and pump applications for radar and ultrasonic transmitters – \nor any other 2-wire 4 to 20 mA devices.",
        "Siemens non-contacting ultrasonic \nsensors and transmitters have active \nface technology which reduces \nmaterial buildup and provides trouble-free, reliable performance. Both \nour transmitters and transducers \n(when combined with a Siemens \ncontroller) feature Process Intelligence, our field-proven echo \nprocessing algorithms, to guarantee \nthe most reliable performance \npossible.",
        "SITRANS LR250 is an excellent choice for liquid \nlevel measurement in storage and process vessels \nto 20 meters (66 ft).",
        "The pressure transmitter SITRANS LH100 is a submersible sensor for\nhydrostatic level measurement.\nThe pressure transmitter measures the liquid levels in tanks, containers, channels and dams. The SITRANS LH100 pressure transmitters are available for various measuring ranges and with explosion\nprotection as an option.",
        "It is generally recommended that the connecting cable of the\nSITRANS LH100 transmitter is connected to the cable box, which\ncan be ordered separately, and secured with the anchoring clamp,\nalso available separately. The cable box has to be installed near the\nmeasuring point.",
        "The SITRANS P200 pressure transmitter measures the gauge and\nabsolute pressure of liquids, gases and vapors. It is made with ceramic measuring cell. The gauge and absolute measuring ranges 1 to 60 bar (15 to\n1000 psi). It can be applied to general applications.",
        "SITRANS TF320 can be used everywhere where temperatures need\nto be measured under particularly adverse conditions and where a\nuser-friendly local display is ideal. Which is why users from all industries have opted for this field device. The rugged enclosure protects\nthe electronics. The stainless steel model is almost completely resistant to sea water and other aggressive substances. The inner\nworkings offer high measuring accuracy, universal input and a wide\nrange of diagnostic options.",
        "The SITRANS TR300 is configured over HART. This can be done using a handheld communicator or even more conveniently with a HART\nmodem and the SIMATIC PDM parameterization software. The configuration data are then permanently stored in the non-volatile memory\n(EEPROM).\nOnce the sensors and power supply have been correctly connected, the transmitter outputs a temperature-linear output signal and the diagnostics LED displays a green light. In the case of a sensor break, the LED flashes red, an internal device fault is indicated by a steady red light.",
        "The FCT010 transmitter delivers true multi-parameter measurements i.e. massflow, volumeflow, standard volumeflow, density,\ntemperature . All with a single Modbus connection.",
        "The SITRANS FS220 is a clamp-on ultrasonic flow system consisting\nof an FST020 transmitter and FSS200 clamp-on sensors.\nThe transmitter classification FST020 describes a basic clamp-on\nultrasonic flowmeter for basic application requirements. Based on\nthe same digitalized platform as the FST030 this system provides\nthe same accuracy and similar functions on a lower cost level. This\nsystem is ideal for water measurement and any application not\nrequiring temperature or viscosity compensation.",
        "SITRANS LR250 Polypropylene lens antenna is a 25 GHz pulse radar\nlevel transmitter for continuous monitoring of liquids and slurries in\nstorage and process vessels including corrosive materials to a range\nof 20 m (65.6 ft).",
        "SITRANS LR250’s unique design allows safe and simple programming using the Intrinsically Safe handheld programmer without\nhaving to open the instrument’s lid.",
        "Wireless data communication via Industrial Wireless LAN (IWLAN) plays an \nimportant role in many areas of the automotive industry in supporting reliable \nand safe operations – such as in controlling robots in the production cells \nwhere body, engine, and drivetrain are brought together or through wireless \nnetworking of heavy-load overhead monorails in logistics. Safety of the \npersonnel is ensured at all times – thanks to real-time communication in \nPROFINET or EtherNet/IP applications, the plant immediately performs an \nemergency stop in critical situations",
        "Humans and robots work hand in hand at the \nassembly lines of car manufacturers. Safety of \npeople plays a crucial role in this interaction. If \na failure occurs, the use of cyclic protocols such \nas PROFINET enables the plant to be stopped \nimmediately via WLAN and PROFIsafe in order to \navoid personnel injury or damage to property.",
        "To fully benefit from all the advantages of \ndigitalization, companies first have to \nachieve complete consistency of their data. \nFully digitally integrated business processes, \nincluding those of suppliers, can help to \ncreate a digital representation of the entire \nvalue chain.",
        "With MindSphere, Siemens offers a cost\u0002effective and scalable cloud platform as a \nservice (PaaS) for the development of applications. The platform, designed as an open \noperating system for the Internet of Things, \nmakes it possible to improve the efficiency \nof plants by collecting and analyzing large \nvolumes of production data.",
        "Totally Integrated Automation (TIA) ensures \nthe seamless transition from the virtual to \nthe real world. It already encompasses all \nthe necessary conditions for transforming \nthe benefits of digitalization into true added \nvalue. The data that will form the digital \ntwin for actual production is generated from \na common base",
        "The SINUMERIK 808D ADVANCED control is a \npanel-based CNC for the lower performance range. \nThe compact and user-friendly entry-level solution is \nused for basic turning and milling applications. Fea\u0002tures such as easy operation, commissioning and \nmaintenance, combined with an optimum cost posi\u0002tion, represent the perfect basis for equipping entry\u0002level CNC machines.",
        "SINUMERIK ONE is the world's first CNC developed from scratch and specifically designed to meet the challenges of digital transformation in the machine \ntool industry. This has led to a paradigm shift, with the digital twin constituting \nan integral part of the control and forming the essential basis for real-world \naction. Machining processes and machine behavior can be simulated in realistic environments.",
        "The new SINAMICS S120 Booksize devices have a 300 percent \noverload capability and combine compactness with power den\u0002sity. The width can be reduced for applications that are dimen\u0002sioned for maximum current with high acceleration levels – or for \npositioning axes demanding a high dynamic performance.",
        "The protective function of protection and switching devices in low-voltage power distribution systems is determined by the correct \nselection of the respective tripping characteristic (fuses, miniature circuit breakers) or TMTU/ETU trip units (air circuit breakers, \nmolded case circuit breakers)",
        "The SIMIT simulation platform enables \ncomprehensive tests of automation \napplications and provides a realistic \ntraining environment for operators \neven before the real startup. This \ncreates opportunities for process optimization and know-how retention, \nwhich results in a reduced commissioning time and significantly shortened time-to-market",
        "COMOS is the engineering tool from \nSiemens for the entire lifecycle of your \nplant. Through direct integration of our \nPIA Lifecycle Portal, we guarantee the \nseamless integration of our field \ndevices in the engineering environment. We can offer you the field \ndevices best suited to your processes, \nproperties and measuring requirements.",
        "FCT030 is based on the latest developments within digital signal\nprocessing technology – engineered for high measuring performance, fast response to step changes in flow, fast dosing applications, high immunity against process noise, easy to install commission and maintain.\nThe FCT030 transmitter delivers true multi-parameter measurements i.e. massflow, volumeflow, standard volumeflow, density,\ntemperature and fraction.",
        "LDS 6 is a diode laser gas analyzer with a measuring principle based\non the specific light absorption of different gas components. LDS 6\nis suitable for fast and non-contact measurement of gas concentra\u0002tions in process or flue gases. One or two signals from up to three\nmeasuring points are processed simultaneously by the central ana\u0002lyzer unit. The in-situ optics enclosures at the individual measuring\npoints are connected to the central unit via fiber optic cables, so\nthat the distance between the installation site of the central unit\nand the measuring points can be up to 700 m. The optics enclos\u0002ures are designed for operation under harsh environmental condi\u0002tions and contain a minimum of electrical components.",
        "Minimized downtimes and optimum utilization of personnel and equipment are important keys to sustained \nsuccess in industrial applications. For this reason it is \nnecessary to detect potential fault sources at an early \npoint in time, and integrate pending maintenance at \nthe right time in the production cycle",
        "Vibration monitoring is the most reliable method for early \ndetection of mechanical damage.",
        "Machining in the press working line takes place in several \nstages on consecutive presses. A particular challenge for \ncondition monitoring results from the successive pressing \nimpacts and the widely varying motor speed during the \npressing cycle. Using appropriate analytical procedures \nand trigger conditions, it is possible to generate informative parameters in the SIPLUS CMS X-Tools analysis software. These allow optimal determination of the mechanical \nconditions.",
        "In order to monitor the main drive train with belt drive, \nflywheel, belt, gearboxes, and bearings in press working \nlines, sensors are mounted at appropriate positions of the \ntrain. The vibration signals recorded by the sensors are \nprocessed further via corresponding hardware components.",
        "SICAR Automation Software is our software platform for shopfloor automation. \nIt includes: \n-\tSoftware library\n-\tTemplate project for PLC and HMI based on TIA Portal\n-\tDocumentation, Implementation Guides, Getting Started\nIt serves as a starting point for you to define your own software standard for control and visualization. It provides you with all core functions that typical production machines require. Due to its open interfaces and modules, you have the option to individualize and extend the SICAR software according to your needs.",
        "Task Lifts are used in the automotive industry to move the car bodies between different levels. The lift can be equipped with a skid conveyor or an electric monorail system. Present belt lifts run the position in the drive to relief the PLC. To increase energy efficiency, drives with energy recovery are used.",
        "Simple roll conveyors with direct on-line operation are often used in conveyor systems. Cabinet products in IP54, which are placed in a cabinet directly at the roll conveyor, are a cost efficient alternative to decentralized drives systems.",
        "The SITRANS Verificator is the next generation in-situ verification\ndevice for use with a various of SITRANS FM flow meters. The battery powered device carries out a complex verification and performance check of the entire flowmeter system. The whole verification\ntest is fully automated and can be controlled using a mobile software application via the Bluetooth interface.",
        "Milltronics MUS operates with products like aggregates, sand, or\nminerals, providing continuous in-line weighing at a minimal cost.\nWith no cross bridge, this versatile unit will fit most conveyor widths\nand standard idlers, and product build-up is reduced.\nThe construction and easy assembly of the MUS ensures quick delivery to meet even the tightest of schedules. Where scales are moved\nfrom conveyor to conveyor, the MUS also provides unmatched flexibility.",
        "The Probe is a short-range integrated ultrasonic level transmitter,\nideal for liquids and slurries in open or closed vessels. The Probe is easy\nto install and maintain, and can be quickly removed for cleaning as\nrequired by the food, beverage and pharmaceutical industries.\n The reliability of the level data is based on the Sonic Intelligence\necho processing algorithms. A filter discriminates between the true\necho and false echoes from acoustic or electrical noises and agitator\nblades in motion. The ultrasonic pulse propagation time to the\nmaterial and back is temperature-compensated and converted into\ndistance for display, analog output and relay actuation.",
        "Pointek CLS100 is a compact, 2-wire, inverse frequency shift capacitance switch for level and material detection in constricted spaces,\ninterfaces, solids, liquids, slurries, and foam; with the ability to tune\nout buildup on probe",
        "The Pointek ULS200 is an ultrasonic non-contacting switch with two\nswitch points for level detection of bulk solids, liquids and slurries in\na wide variety of industries; ideal for sticky materials",
        "Status monitoring with 3-stage alarm concept is provided by \nthe intelligent electropneumatic SIPART PS2 positioner. It is equipped\nwith additional monitoring functions. The status alarms derived\nfrom these monitoring functions signal active faults of the valve\nwith grading in the form of traffic light signaling. The status alarms\nare symbolized by a wrench in the colors green, yellow and red :\n• Maintenance required (green wrench)\n• Urgent maintenance demanded (yellow wrench)\n• Imminent danger of valve failure or general failure (red wrench)",
        "Valve Signature:\nWith pressure sensor-aided Valve Signature, the characteristic curve\nof the valve can be recorded, saved in the device (max. 10 charac\u0002teristic curves) and displayed in PDM, for example. The reference\ncharacteristic curve is recorded at the beginning directly during initialization. Based on the exportable data, friction values, spring\ncharacteristics, hysteresis, breakout pressures can be determined. If\nthe test is regularly repeated, characteristic curves can be compared\nwith one another and changes over time can be displayed as the\nbasis for a predictive maintenance approach.",
        "Electronic Device Description (EDD) is a proven way to describe the\nbehavior and functionality of field instruments and other automation components.",
        "HART is a widely used communication standard for field devices. The HART devices are specified by the FieldComm Group.\nThe HART standard expands the analog 4 to 20 mA signal to modulated, industry-tested and digital signal transmissions.",
        "Today, distributed automation solutions based on open field buses\nare state-of-the-art in large areas of the process engineering\nindustry. It is only with fieldbuses that the functional benefits of\ndigital communication can be put to full use, e.g. better resolution\nof measured values, diagnostics options and remote parameterization.",
        "The transfer technology of the FOUNDATION Fieldbus is tailored to\nthe needs of the process industry. Interoperability between field\ndevices from different manufacturers and remote parameterization\nof the field devices during operation are guaranteed by the standardized communication services.",
        "SITRANS FST090 clamp-on ultrasonic flowmeter\nThe portable clamp-on ultrasonic flow measurement system\nSITRANS FS290 is formed by the SITRANS FST090 portable clamp-on\nflowmeter with FSS200 sensors.\nThis system represents the next generation of digital flow measurement which allows you to easily measure or check flows in pipes.",
        "Flow measurement with the SITRANS FVA250 is performed according to the float principle. The flowing medium lifts the conical float\nin the measuring ring. This increases the ring gap until an equilibri\u0002um is established between the buoyant force of the medium and\nthe weight of the float. The height of the float is directly proportion\u0002al to the flow rate. The movement of the float is transmitted from\none magnet to another magnet in the display unit outside of the\nmeasuring tube",
        "Due to its full metal design, the SITRANS FVA250 variable area\nmeter with a standard length of 250 mm (9.84 inch) can be used to\nmeasure many different types of liquids and gases passing through\nclosed piping. The robust design means that it can also be used in\nharsh conditions. The various types of flange connections, linings\nand float materials satisfy the requirements of the pharmaceutical\nand chemical industries.",
        "HydroRanger 200 is an ultrasonic level controller for up to six\npumps and provides control, differential control, and open channel\nflow monitoring.",
        "The SIPART PS100 electropneumatic positioner is used to control\nthe process valve or damper position of pneumatic linear or part\u0002turn actuators. The SIPART PS100 regulates the process valve\naccording to the setpoint.",
        "The EIA‑485 transmitter isolating power supply consists of a compact plastic enclosure (IP20) in the SIMATIC S7‑1200 design, and is\nequipped with plug-in screw terminals. On the front are a green\nLED for indicating the auxiliary power supply status and a yellow\nLED for signaling communication. The push-in screw terminals are\njumpered on the EIA‑485 transmitter isolating power supply, allowing the power supply and primary-side communication to further\nSITRANS I300 devices to be looped through.",
        "Distributed automation solutions based on open fieldbuses\nare standard in many areas of the manufacturing industry and in\nprocess engineering. It is only with fieldbuses that the functional\nbenefits of digital communication can be put to full use, e.g. better\nresolution of measured values, diagnostics options and remote\nparameterization.\nToday, PROFIBUS is the most successful open fieldbus with a large\ninstalled base for a wide range of applications. Standardization\naccording to IEC 61158 / EN 50170 provides you with future protec\u0002tion for your investment.",
        "PROFIBUS is suitable for fast communication with distributed I/O\n(PROFIBUS DP) in production automation as well as for communica\u0002tion tasks in process automation (PROFIBUS PA). It is the first field\u0002bus system that meets the demands of both areas with identical\ncommunication services.\nThe transfer technology of PROFIBUS PA is tailored to the require\u0002ments of the process industry. The standardized communications\nservices guarantee interoperability between multi-vendor field\ndevices and remote configuration of the field devices during opera\u0002tion.",
        "SITRANS serve IQ is an on-premise application that acquires measurement data sent by email (CSV file attachments) from remote sensors.\nThe data is stored locally on an Industry PC and visualized in charts and tables. If configured, authorized users can access this on-premise\napplication via the Internet.\nOptionally, users can create and send customized reports on measurement data and log events in a log-book to, for example, document services. An interface for forwarding data to a SCADA system using the telemetry protocol IEC 60870-5-104 is also available.",
        "With its tested fire barrier and functional endurance in case of fire, \nthe BD2 system ensures safety even in an emergency. Thanks to its \ncompact design, it requires surprisingly little space and ensures safety \nnot just during system operation but also during installation: \nThe anti-rotation feature and guided installation make it fast and easy \nto install. Because the busbar trunking system is communication\u0002capable, you will benefit from fully transparent operation with the \nadvantage of a high level of system availability.",
        "SITRANS WW100 is a high-accuracy, low-capacity weighfeeder used\nfor minor ingredient additives. It is one of the most accurate in-motion weighing\nsystems on the market. It is specially designed for high accuracy on\nlight loading processes. The design eliminates material buildup to\nensure accurate, reliable measurement.\nThe unique long length platform weigh bridge mounts directly to a\ncorrosion-resistant platform load cell. An adjustable mechanical\nshear gate profiles the material and fixes the correct material bed\ndepth for a given material particle size. The belt speed can be auto\u0002matically adjusted to attain the correct feed rate.",
        "EPEC_QT’s innovative switchboard and solar recombiner \ntechnology combined with their engineering services \nprovides multiple advantages to their customers, including a \nreduced footprint and the ability to make a direct connection \nto the transformers that convert the sun’s power to usable \nelectrical energy. The company’s solar-specific UL 891 dead \nfront switchboard boasts a compact innovation that results in \na 40% smaller implementation. This reduction is enabled by a \ndesign that minimizes cable sizes, which reduces costs and \ntime to install.",
        "Solar applications often exist in harsh environments, typically in \nremote locations. To avoid costly downtime, equipment must \nbe reliable and able to withstand high heat. A prime example of \nthe advantages of electronic trip units is EPEC_QT’s use of \nSiemens 3VA6 molded case circuit breakers to protect solar \nimplementations from overcurrent conditions. Not only do 3VA \nbreakers prevent nuisance tripping in these environments, but \nthey also prevent potential fires in unmanned installations, \nwhich can damage expensive equipment",
        "Siemens goal is to make it easier for companies like EPEC_QT to \nselect and configure their electrical solutions. EPEC_QT \nbenefitted from Siemens Totally Integrated Automation (TIA) \nwhich saved programming and design time for faster time-to\u0002market and less engineering programming costs",
        "Companies need industrial communication to \ncontrol machines and plants. Optimal utilization of \nthe data generated in production also requires that \nOperational Technology (OT) and Information Tech\u0002nology (IT) networks seamlessly interact. With our \ncomplete range of services and solutions for indus\u0002trial networks, we help you lay an optimal founda\u0002tion for digitalization and accompany you from the \nvery start as you navigate the digital transformation",
        "Siemens Industrial WLAN enables secure and reliable \nwireless connections for industrial applications. \nBut even the best wireless network components \nalone aren’t enough to create a state-of-the-art \nindustrial wireless network. Expertise in network \ndesign and implementation is just as important.",
        "SIWAREX WP321 is a versatile and flexible weigh beam for the\nseamless integration of a static scale into the SIMATIC automation\nenvironment.\nThe weighing electronics are integrated within the SIMAT\u0002IC ET 200SP system series and use all the features of a modern auto\u0002mation system, such as integrated communication, operator control\nand monitoring, diagnostics units and the project planning tools in\nthe TIA portal, SIMATIC Step 7, WinCC flexible and PCS7.\nIn conjunction with the digital SIWAREX DB junction box, up to four\nconnected load cells can be diagnosed separately. This enables the\nweigh beam module to detect the failure of individual load cells\nand, in the event of an error, to provide relevant load cell data such\nas order number and location designation directly in the CPU or at\nthe HMI. This increases the operational reliability of the scale,\nreduces downtimes, makes commissioning easier and simplifies servicing.",
        "The primary task of the weighing electronics is to determine the\ncurrent weight and force values on the basis of signals supplied by\nthe connected sensors. Thanks to the seamless integration into the\nSIMATIC environment, values can be processed directly and in any\navailable programming language of the CPU. If the freely selectable\nand internally monitored values are exceeded or undershot, this is\nreported directly to the controller. A variety of status and diagnostic\ninformation can also be read out and evaluated in the CPU without\ndifficulty.",
        "SIWATOOL is a service software tool which enables you to calibrate\nthe module quickly and efficiently on site, set or reset parameters,\nor perform diagnostics in the event of a fault. Furthermore, com\u0002plete backup files can be created for the scales, which can be\nuploaded to a new module with a few mouse clicks, so that the\nmodule continues to operate exactly as it did before the backup,\nwithout the need for any recalibration. It is even possible to upload\nconfiguration files that were created offline, or to read out the error\nbuffer. No special SIMATIC knowledge is required to use SIWATOOL.",
        "The SIWAREX WL260 SP-S AE single point load cell is suitable for the\nsmallest load ranges from 0.3 kg to 3 kg and platform sizes up to\n200 mm x 200 mm (7.87 × 7.87 inch). The load cell can be used in\nhigh resolution scales. The error amounts to a maximum of 0.010 %\nin relation to the rated characteristic value.",
        "The entire SIPROCESS GA700 device is configured in a modular fashion and consists of a basic unit and at least one – maximum two –\nmodules. It can optionally be fitted with up to two interface mod\u0002ules.",
        "The ULTRAMAT 7 module functions according to the NDIR dual\u0002beam differential mode process and measures gases whose absorption bands in the infrared wavelength range are between 2 and\n9 µm, such as CO, CO2, CH4, SO2 or NO. Up to two components can be measured per module",
        "A source with a temperature of approx. 600 °C generates infrared\nradiation which is emitted in the beam splitter. The beam splitter\nacts as a filter chamber and divides the beam equally between the\nsample gas and reference gas compartments.\nThe chopper produces a periodic modulation of the infrared radiation, and thus enables relaxation of the detector.\nThe reference beam passes through the reference chamber and\nenters the detector chamber virtually unattenuated. The detector\nchamber is filled with a precisely defined concentration of the gas\ncomponent to be measured. The sample beam, in contrast, passes\nthrough the sample chamber filled with sample gas and enters the\ndetector chamber attenuated to various degrees. The degree of\nattenuation depends on the respective sample gas concentration.\nThe detector is designed as a double-layer detector. The detector\nlayer at the source end serves primarily to absorb the middle of the\nband. The band edges, however, are absorbed equally by both of\nthe layers.",
        "Oxygen is highly paramagnetic. This outstanding property of paramagnetism is used as a physical measuring effect for oxygen analysis.\nOxygen molecules in an inhomogeneous magnetic field always\nmove toward the higher field strength. This results in a higher oxy\u0002gen concentration where the field strength is higher (higher oxygen\npartial pressure). If two gases with differing oxygen content are\ncombined in a magnetic field, a (O2 partial) pressure difference\narises between them.\nSince the measuring effect is always based on the difference of the\noxygen content of the two gases, one refers to the sample and reference gases",
        "To determine the cross-interferences of accompanying gases with\nseveral interfering gas components, you must know the sample gas\ncomposition.",
        "The thermal conductivity of most gas mixtures has a non-linear\nresponse. Even ambiguous results can occur in specific concentra\u0002tion ranges, e.g. with H2 in He mixtures.\nIn addition to the zero offset, the accompanying gas can also affect\nthe characteristic curve. For most gases, however, the effect on the\ncharacteristic curve is negligible.",
        "SITRANS TDL is an in-situ gas analyzer and consists of a pair of cross\u0002duct sensor units which are directly installed at the measuring point\nin the plant. The operating principle of SITRANS TDL is based on\ntunable diode laser spectroscopy (TDLS). This makes SITRANS TDL\nthe ideal solution for fast and non-contact measurements of gas\nconcentrations. The analyzer can be intuitively monitored and con\u0002trolled locally via its human machine interface (HMI) and from\nremote using a standard web browser. A large variety of communic\u0002ations interfaces enables the seamless integration into digital con\u0002trol systems.",
        "As a result of Beer-Lambert’s law, the absorption of laser light depends on the optical path length within the sample gas. Therefore, the pre\u0002cision of the effective optical path length measurement can influence the precision of the total measurement. Since the sensor optics on the\nprocess side are normally purged to keep them clean for a longer period, the expansion of the mixed zone between the purging medium and\nthe process gas as well as the latter's concentration distribution must be considered. In a typical in-situ installation with an optical path\nlength of several meters, the influence of the purging gas on the effective path length can be ignored. The maximum possible path length\nand dust load mutually affect each other: the higher the dust load in the process, the shorter the maximum possible path length.",
        "Claroty is an industrial cybersecurity company. Trusted by the world’s largest enterprises, Claroty helps \ncustomers reveal, protect, and manage their OT, IoT, and IIoT assets. The company’s comprehensive \nplatform connects seamlessly with customers’ existing infrastructure and programs while providing a full \nrange of industrial cybersecurity controls for visibility, threat detection, risk and vulnerability management, and secure remote access – all with a significantly reduced total cost of ownership. Claroty is \nbacked and adopted by leading industrial automation vendors, with an expansive partner ecosystem and \naward-winning research team.",
        "Switches are active network components that support the structuring \nof an industrial communication network into electrical or optical line, \nstar and ring structures. They specifically distribute data to the defined \naddressees and structure the data traffic. Data throughput and network performance are increased.",
        "Milltronics MCS is a compact, rugged, modular, heavy-duty belt\nscale for use in mobile crushers and aggregate screening plants.\nIdler not included with belt scale.",
        "Milltronics SF500 is a full feature integrator for use with solids flow\u0002meters. It operates with any solids flowmeter with up to\ntwo strain gauge load cells or LVDT sensor. The SF500 processes\nsensor signals for accurate flow rate and totalized weight of bulk\nsolids. It can take on lower level control functions traditionally\nhandled by other devices, and it supports popular industrial communication buses. Its proven load cell balance function eliminates\nmatching of load cells.",
        "The load cell is ideal for use in tank weighing, hybrid weighing\nmachines or suspended container weighing. It is made of stainless\nsteel and therefore also suitable for use in harsh environments.\nThe SIWAREX WL250 ST-S SA is suitable for both s-type tension and\ncompression loads. The preferred direction of measurement is tension, with factory calibration for the load cells. For compression\napplications, adherence to the characteristic values and error limits cannot be guaranteed.",
        "SmartLinx modules provide direct digital connection to popular\nindustrial communications buses with true plug-and-play compatibility with products manufactured by Siemens. With the addition of a SmartLinx module, Siemens instruments can\nbe connected to a variety of industrial communications networks.\nThey’re fast and easy to install, and can be added at any time. The\nmodule simply plugs into the socket on any SmartLinx enabled\nproduct. They require no secondary private buses or gateways and\nno separate wiring. There are no extra boxes to connect to your net\u0002work so there’s a minimum load on engineering and maintenance\nstaff. SmartLinx provides all data from the instrument, including meas\u0002urement and status, and allows changes to operation parameters to\nbe done over the bus or telemetry link. The user can select which\ndata in the application layer to transfer over the bus. This selection\nsaves bandwidth and memory and optimizes data throughput and\nspeeds up the network, enabling you to connect more instruments\nto your network\n\u0002",
        "The junction box of die-cast aluminum consists of a lower section\nand cover. The enclosure is dust-protected and splashproof according to IP66 degree of protection. The cables are fed in through metric cable glands. In the enclosure, screw terminals are fixed onto a\nconnection board.",
        "The bending beam load cell is particularly suitable for use in small\nhopper and platform scales. The measuring element is a double bending beam made of stainless\nsteel to which 4 strain gauges are applied.\nThe strain gauges are arranged so that two are stretched and two\nare compressed.\nUnder the influence of the load acting in the measuring direction,\nthe spring bodies and therefore the friction-locked strain gauges are\nelastically deformed. This generates a measuring signal voltage that\nis proportional to the load.",
        "SIWAREX U is a versatile weighing module for all simple weighing\nand force measuring tasks. The compact module can be integrated\ninto SIMATIC automation systems without any problems. Complete\ndata access is then possible via the SIMATIC.U It is available with either one or two measuring channels.\nOne measuring channel is required for each set of scales.\nThe primary task of SIWAREX U is the measurement of sensor\nvoltage and the conversion of this measurement into a weight\nvalue. The signal can also be digitally filtered if required.",
        "The SIWAREX DB digital junction box has a die-cast aluminum or\nstainless steel enclosure. The enclosure is dust-protected and\nsplashproof according to the IP66 degree of protection.\nCables are fed in through metric cable glands. Plug-in terminals\nreduce wiring effort during commissioning. Connection to\nSIWAREX WP electronic weighing systems is via the RS 485 inter\u0002face.",
        "The SIMATIC IOT2000 SG-Shield is the simple solution for remotely\nviewing measured values from load cells based on strain gauges.\nThe load cell cable simply connects directly to the shield. The system digitizes the analog data and sends it to the cloud via the\nSIMATIC IOT2050 Gateway. This allows you to retrieve the filling\nlevels from your customers at any time and adjust your delivery\nroutes accordingly.",
        "Inventory management is a necessary task in virtually every value\nchain. Inventories are required whenever material is processed, produced, or assembled. SITRANS store IQ is an inventory management\napp based on Siemens MindSphere, that records measurements and\ndata from various types of instrumentation, including a level device\nat a process tank or scales mounted in storage shelves.",
        "Siemens Industry leading switchboards provide a solution \nfor a wide range of applications. From 400A at 120V \nthrough 6000A at 600V.\nEvery aspect of the design of Siemens switchboards has\nbeen aimed at improving layout convenience, reducing \ninstallation costs and minimizing the impact and cost of \nchanges to the system.\nSiemens switchboards provide a rugged design and the\nflexibility necessary in electrical systems for all types of\napplications. Some examples are:\n- Commercial buildings\n- Industrial plants\n- Retail chain stores\n- Health care facilities\n- High-rise complexes",
        "Integrated Power Systems (type IPS) switchboards integrate \nelectrical equipment that’s typically mounted in separate \nenclosures into a single assembly.\nThe IPS switchboard design results in a large reduction in \nfootprint in an electrical room. In addition to a reduced \nfootprint, factory installed wiring significantly reduces \ninstallation time and cost",
        "Introducing Siemens SmartGear Mobile: Using a phone or tablet you can monitor and configure \ndevices, open/close breakers and activate arc flash maintenance mode while outside the arc flash \nhazard boundary. This allows users to reduce the hazards associated with gear interaction.",
        "With the help of rock-solid 3WA air circuit breakers,\nyour power distribution system will benefit from \nthe reliable protection you know and trust. Benefit \nfrom a comprehensive portfolio that meets every \nrequirement and suits every application. Consistent, end-to-end circuit breaker portfolio \nup to 1,150 V AC\nThree sizes with rated currents of 630 A \nto 6,300 A for AC applications\nOne frame size up to 4,000 A for DC applications\nHigh breaking capacity ICU of 55 kA to 150 kA \nat 500 V AC\nSimple extension of functions, thanks to uniform \naccessories for all frame sizes",
        "The SCALANCE M portfolio consists of industrial routers for wireless or wired access. The \nproducts facilitate the efficient connection of stationary and mobile stations to a control \ncenter. Extensive security functions, such as firewalls and VPN encryption, offer protection \nduring transmission of data.",
        "Powerful industrial communication networks are the indispensable \nbackbone of every digital factory. Planning and implementing industrial \nnetworks requires specialist knowledge that you can acquire first-hand \nthanks to the comprehensive Industrial Networks Education training and \ncertification program. After passing an exam, you’re given a certificate \ndocumenting your knowledge in the context of the training program. \nThis establishes you as a member of a group of distinguished specialists \nin the field of industrial networks and provides proof of your knowledge.",
        "The function of the SIPROCESS UV600 gas analyzer is based on UV\nresonance absorption spectrometry. It also is used to measure very\nlow NO, NO2,SO2or H2S concentrations in gases. The measuring principle of the SIPROCESS UV600 is based on the molecule-specific absorption of gases in the ultraviolet wavelength range.\nRadiation of a wavelength appropriate to the measurement is passed through the sample, and the selective absorption which is proportional\nto the concentration of the measured component is determined",
        "The standardized Set GGA (Generator Gas Analyzer) has been specially designed for monitoring hydrogen-cooled turbo generators. With the dual benefit of being simple to handle\nand having low initial investment costs. Another feature of the GGA is a protective cabinet for the analyzers.\nThis provides a compact location where the system can be easily\ninstalled, and offers protection against dust and water.",
        "The HM-1400 TRX not only monitors the performance of the mercury separators by measuring the total mercury concentration, but\nalso reports and registers (also online) any violation of the high limits. As a result it is often possible to intervene directly in the process\nof the plant to be monitored and thus ensure reliable compliance\nwith the specified limit values.",
        "The Analyzer System Manager (ASM) is a PC-based operator control\nand monitoring system for monitoring, controlling and optimizing\nanalyzers in subsystems or in the complete plant. The relevant\ninformation from different analyzers is collected via various com\u0002munications protocols in software. Using the PC's user-friendly\noperator interface, it is possible to access measured value trends,\ndevice statuses and statistical evaluations, for example, or to start\ntest routines for validation of the results. The software analyzes the\ncollected data for possible problems and provides the user addition\u0002al information.",
        "The D‑R 808 device operates according to the forward-scattering\nprinciple. The concentrated and modulated light from a laser diode\npenetrates the measuring volume. The light scattered by the dust\nparticles in the forward direction is measured and evaluated.\nBy means of a gravimetric reference calibration, a calibration curve\ncan be stored on the integrated electronics and the measured signal\ncan be converted into a dust concentration in mg/m³",
        "The D-EMS 2000 CS compact system is designed for small to medium sized industrial plants whose emission data, immission data or\nprocess data must be recorded in line with public authority regulations for measured data logging. Benefits : Continuous monitoring of 1 to 12 components, connected via bus\ncommunication or hard-wired, Compact system, no additional evaluation PC required.",
        "The D-FL 100 continuously determines the sample gas speed for\nreliable emission monitoring, even in hot or aggressive gases, and\nin small to large flues. The D-FL 100 can be used for reliable emission monitoring even in hazardous areas. The measuring system is\ntherefore ideal for process control and process optimization.",
        ], 
}

def tester(model, test):
    results = []
    for query, passages in test.items():
        # Embedding generation
        results.append(f"Query: {query}\n")
        query_embedding = model.encode(query, convert_to_tensor=True)
        passage_embeddings = model.encode(passages, convert_to_tensor=True)
        scores = util.dot_score(query_embedding, passage_embeddings)[0]
        sorted_scores = sorted(zip(passages, scores), key=lambda x: x[1], reverse=True)
        for passage, score in sorted_scores[:3]:  # Top three 
            # print(f"Passage: {passage} \nScore: {score:0.02f}")
            results.append(f"Passage: {passage}\nScore: {score:0.02f}\n")
    return results

# tester(model, test)


def display_results(): 
    sbert_results1 = tester(model1, test)
    sbert_results2 = tester(model2, test)
    result_text = "\n".join(["Model Results no training:"] + sbert_results1 + ["Model Results 3500 steps training:"] + sbert_results2)
    text_area.config(state=tk.NORMAL)
    text_area.delete('1.0', tk.END)
    text_area.insert(tk.INSERT, result_text)
    text_area.config(state=tk.DISABLED)

root = tk.Tk()
root.title("Model Comparison Tool")

frame = tk.Frame(root)
frame.pack(padx=20, pady=20)

text_area = scrolledtext.ScrolledText(frame, wrap=tk.WORD, width=100, height=20, font=("Times New Roman", 12))
text_area.pack()

button = tk.Button(frame, text="Run Comparison", command=display_results)
button.pack(pady=10)

root.mainloop()